Add color to git-close-current-branch

diff --git a/git-close-current-branch b/git-close-current-branch
--- a/git-close-current-branch
+++ b/git-close-current-branch
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+. "${BASH_SOURCE[0]%/*}"/utils.bash
+
 usage() {
     echo "Usage: git close-current-branch [MAINLINE]"
     echo
@@ -19,48 +21,11 @@ usage() {
     echo "  > git fetch && git close-current-branch"
 }
 
-die() {
-    local code=1
-    if (( $# > 1 )); then
-        code=$1
-        shift
-    fi
-    (( $# > 0 )) && printf "%s\n" "$1" >&2
-    exit "$code"
-}
-
-set_color() {
-    test -t 1 || return 0
-    case "$1" in
-        reset)
-            tput sgr0;;
-        black)
-            tput 0;;
-        red)
-            tput 1;;
-        green)
-            tput 2;;
-        yellow)
-            tput 3;;
-        blue)
-            tput 4;;
-        magenta|purple)
-            tput 5;;
-        cyan)
-            tput 6;;
-        white)
-            tput 7;;
-        *)
-            echo "set_color: unkown color '$1'" >&2
-            return 1
-    esac
-}
-
 detectMainline() {
     local branch
     if ! branch=$(git config --get close-current-branch.mainline); then
-        echo "warning: no mainline provided, assuming 'develop'" >&2
-        echo "note: set config value close-current-branch.mainline to suppress this warning" >&2
+        color yellow "warning:" reset " no mainline provided, assuming " cyan "develop" reset >&2
+        color yellow "note:" reset " set config value " yellow "close-current-branch.mainline" reset " to suppress this warning" >&2
         branch=develop
     fi
     printf "%s\n" "$branch"
@@ -77,9 +42,7 @@ while (( $# > 0 )); do
             break
             ;;
         -*)
-            echo "unknown flag $1" >&2
-            usage >&2
-            exit 1
+            die 2 "unknown flag $1" "$(usage)"
             ;;
         *)
             break
@@ -89,22 +52,16 @@ while (( $# > 0 )); do
 done
 
 mainline=$1
-if (( $# > 1 )); then
-    echo "expected at most 1 parameter, found $#" >&2
-    usage >&2
-    exit 2
-fi
+(( $# > 1 )) && die 2 "expected at most 1 parameter, found $#" "$(usage)"
 
 git rev-parse --git-dir >/dev/null || exit
 
-if test -z "$mainline"; then
-    mainline=$(detectMainline) || exit
-fi
+[[ -z $mainline ]] && { mainline=$(detectMainline) || exit; }
 mainline=$(git rev-parse --revs-only --symbolic-full-name "$mainline" --) || exit
-test -n "$mainline" || die "error: unknown branch '$mainline'"
+test -n "$mainline" || die "unknown branch '$mainline'"
 
 HEAD=$(git rev-parse --revs-only --symbolic-full-name HEAD --) || exit
-test "$HEAD" != "HEAD" || die "error: detached HEAD"
+test "$HEAD" != "HEAD" || die "detached HEAD"
 HEADcommit=
 eval "$(git for-each-ref --count=1 --shell --format='
     HEADname=%(refname:short)
@@ -112,7 +69,7 @@ eval "$(git for-each-ref --count=1 --shell --format='
     HEADupstream=%(upstream)
     HEADupstreamname=%(upstream:short)
 ' -- "$HEAD")"
-test -n "$HEADcommit" || die 3 "error: couldn't find ref information for HEAD ($HEAD)"
+test -n "$HEADcommit" || die 3 "couldn't find ref information for HEAD ($HEAD)"
 
 ref=
 eval "$(git for-each-ref --count=1 --shell --format='
@@ -122,32 +79,32 @@ eval "$(git for-each-ref --count=1 --shell --format='
     upstream=%(upstream)
     upstreamname=%(upstream:short)
 ' -- "$mainline")"
-test -n "$ref" || die "error: no such branch '$mainline'"
-test "$ref" != "$HEAD" || die "error: $refname is currently checked out"
+test -n "$ref" || die "no such branch '$mainline'"
+test "$ref" != "$HEAD" || die "$refname is currently checked out"
 
 if ! git merge-base --is-ancestor "$HEADcommit" "$commit"; then
     # mainline does not contain our branch
-    test -n "$upstream" || die "error: $refname does not contain HEAD"
+    test -n "$upstream" || die "$refname does not contain HEAD"
 
     upstreamcommit=$(git rev-parse --verify "$upstream") || exit
     git merge-base --is-ancestor "$HEADcommit" "$upstreamcommit" ||
-        die "error: neither $refname nor $upstreamname contain HEAD"
+        die "neither $refname nor $upstreamname contain HEAD"
 
     # but upstream of mainline does
-    echo "Updating mainline $refname with $upstreamname..."
+    color magenta "Updating" reset " mainline " cyan "$refname" reset " with " cyan "$upstreamname" reset "..."
 
     git merge-base --is-ancestor "$commit" "$upstreamcommit" ||
-        die "error: $refname contains commits not found in $upstreamname"
+        die "$refname contains commits not found in $upstreamname"
 
     git update-ref -m "git close-current-branch" "$ref" "$upstreamcommit" "$commit" || exit
 fi
 
-echo "Checking out $refname..."
+color magenta "Checking out " cyan "$refname" reset "..."
 git checkout "$refname" || exit
 
-echo "Deleting $HEADname..."
+color magenta "Deleting " cyan "$HEADname" reset "..."
 git update-ref -m "git close-current-branch" -d "$HEAD" "$HEADcommit" || exit
 
 if test -n "$HEADupstream" && git rev-parse --quiet --verify "$HEADupstream" >/dev/null; then
-    echo "warning: upstream $HEADupstreamname still exists" >&2
+    color yellow "warning:" reset " upstream " cyan "$HEADupstreamname" reset " still exists" >&2
 fi
